from collections.abc import Mapping
from typing import Any

from silisocs.runtime.types import ActionOutput, ActionSpec

action_spec_ignored: Any
ActionSpecIgnored: Any
basic_associative_memory: Any
ComponentContextMapping: Any
ComponentEntity: Any
concat_act_component: Any
concordia_location: str
constant: Any
entity_agent_with_logging: Any
entity_component: Any
entity_lib: Any
EntityAgentWithLogging: Any
interactive_document: Any
language_model: Any
ListMemoryBank: Any
make_observation_component: Any
memory_comp: Any
observation: Any
prefab_lib: Any
question_of_recent_memories: Any
scripted_act: Any
ScriptedActComponent: Any

class ConcordiaAgentAdapter:
    def __init__(self, target: Any, *, model: Any | None = None) -> None: ...
    @property
    def name(self) -> str: ...
    def observe(self, observation: str) -> None: ...
    def initialize(self, context: Any) -> None: ...
    def act(self, action_spec: ActionSpec) -> ActionOutput: ...

class ConcordiaGameMasterAdapter:
    def __init__(self, target: Any, *, name: str | None = None) -> None: ...
    @property
    def name(self) -> str: ...
    def initialize(self, *, agents: Any, context: Any) -> None: ...
    def update(self, *, step: int, agents: Any, context: Any | None = None) -> None: ...
    def acting_agents(self, candidate_agents: Any) -> list[str]: ...
    def action_prompt(self, agent_name: str) -> ActionSpec: ...
    def make_observation(self, agent_name: str) -> str: ...
    def resolve_action(self, agent_name: str, action: ActionOutput) -> str: ...

class SocialConcatActComponent:
    @staticmethod
    def _format_prompt(prompt: str, name: str) -> str: ...
    def get_action_attempt(self, contexts: Mapping[str, str], action_spec: Any) -> Any: ...

def extract_structured_response(text: str) -> dict[str, Any] | None: ...
def create_memory_bank(*args: Any, **kwargs: Any) -> Any: ...
def deterministic_sentence_embedder(text: str) -> Any: ...
def make_concordia_memory_bank(memory_backend: str = "list") -> Any: ...
def __getattr__(name: str) -> Any: ...
