defaults:
  - oasis/sim: oasis_base  # OASIS simulation base config
  - social_media: oasis_twitter  # Twitter platform
  - scenario: oasis_twitter_infoprop
  - _self_

experiment_name: oasis_twitter_infoprop
