# @package _global_
description: >-
  A small-town mayoral election (Storhampton) with two candidates on opposite
  sides of economic vs. environmental policy. Studies partisan opinion dynamics,
  media framing effects, and voter persuasion on social media. Includes a news
  agent and rich external persona pipeline.
scenario_name: election
jobname_format: "N${num_agents}_T${num_steps}_${experiment_name}_${run_name}"

setting:
  name: Storhampton
  background:
  - Storhampton is a small town with a population of approximately 2,500 people.
  - Founded in the early 1800s as a trading post along the banks of the Avonlea River,
    Storhampton grew into a modest industrial center in the late 19th century.
  - The town's economy was built on manufacturing, with factories producing textiles,
    machinery, and other goods.
  - Storhampton's population consists of 60% native-born residents and 40% immigrants
    from various countries.
  - Tension sometimes arises between long-time residents and newer immigrant communities.
  - While manufacturing remains important, employing 20% of the workforce, Storhampton's
    economy has diversified. A significant portion of the Storhampton population has
    been left behind as higher-paying blue collar jobs have declined, leading to economic
    instability for many.
  - The Storhampton poverty rate stands at 15%.

event:
  name: Election day
  context: "Storhampton Mayoral Election Campaign: Bill Fredrickson campaigns on providing\
    \ tax breaks to local industry and creating jobs to help grow the economy.\nBradley\
    \ Carter campaigns on increasing regulation to protect the environment and expanding\
    \ social programs.\nThe upcoming election has become a heated affair.\nSocial\
    \ media has emerged as a key battleground in the race, with both candidates actively\
    \ promoting themselves and engaging with voters.\nVoters in Storhampton are actively\
    \ participating in these social media discussions.\nSupporters of each candidate\
    \ leave enthusiastic comments and share their posts widely.\nCritics also chime\
    \ in, for example attacking Bill Fredrickson as out-of-touch and beholden to corporate\
    \ interests,\n or labeling Bradley Carter as a radical who will undermine law\
    \ and order.\nThe local newspaper even had to disable comments on their election\
    \ articles due to the incivility.\nVoters in Storhampton are actively getting\
    \ the latest local election news from Storhampton Gazette's social media account.\n"

data:
  news_file: v1_news_bill_bias
  use_news_agent: with_images
