# src/conf/config.yaml
defaults:
  - sim: base
  - social_media: mastodon
  - scenario: election
  - _self_

hydra:
  job:
    name: ${scenario.jobname_format}_${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: src/scenarios/${scenario.scenario_name}/outputs/${scenario.jobname_format}
  output_subdir: configs/${scenario.jobname_format}

experiment_name: independent